spring:
  application:
    name: dubbo-gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.40.237:8848
    gateway:
      server:
        webflux:
          routes:
            - id: user_service_route
              uri: lb://dubbo-user-service
              predicates:
                - Path=/user/**

            - id: order_service_route
              uri: lb://dubbo-order-service
              predicates:
                - Path=/order/**

server:
  port: 7788

# Sentinel 配置
sentinel:
  transport:
    dashboard: localhost:8080  # Sentinel Dashboard 地址
    port: 8719  # 与控制台通信的端口
  eager: true  # 启动时立即初始化

logging:
  level:
    com.alibaba.csp.sentinel: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.web.reactive: DEBUG